site_name: Ariel Sánchez - Technical Writer
nav:
  - Home: index.md
  - Education: education.md
  - Experience: experience.md
  - Skills: skills.md
  - Selected Past Work: selected_past_work.md
  - Contact: contact.md

theme:
  name: material
  logo: images/Dallas_Cowboys_Logo.png
extra_css:
  - css/extra.css